modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ochotonida/artifacts/issues"

[[mods]]
modId="artifacts"
version="1.15.2-2.5.0"
displayName="Artifacts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/artifacts"
logoFile="logo.png"
description='''Adds various new powerful uncraftable items to make exploration a bit more interesting'''

[[dependencies.artifacts]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.artifacts]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0.2.4,)"
    ordering="AFTER"
    side="BOTH"